server:
  port: 8081

spring:
  profiles:
    active: local
    include: oauth

  jpa:
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        ddl-auto: create
        dialect: org.hibernate.dialect.MySQL57Dialect
        format_sql: true
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/trip100
    username: root
    password : 2549


  mustache:
    suffix: .mustache
    prefix: classpath:/templates/

  session:
    store-type: jdbc
    jdbc:
      initialize-schema: always